### ISSUE TITLE
aggregation code 

### ISSUE THREAD

**Issue by monajalal** [sedab/PathCNN#1]
Hello
Thanks a lot for open-sourcing your code. Could you please point me to the part of your code that takes care of the following in your article?

Thanks a lot,
Mona Jalal

https://www.biorxiv.org/content/10.1101/633123v1.full.pdf
![Screen Shot 2022-05-20 at 10 42 45 PM](https://user-images.githubusercontent.com/1892917/169631253-4c350391-23d1-4f70-b9de-a389a1a7d10e.png)

**Comment by ncoudray** [comment]
Hi - step 3, code for ROC curve
https://github.com/ncoudray/DeepPATH/tree/master/DeepPATH_code#code-for-roc-curves

Best,
N.
